//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vault.rc
//
#define IDD_DIRECTORY_DIALOG            101
#define IDD_LIST_DATASOURCES            103
#define IDD_USER_INPUT                  107
#define IDD_FILE_DIALOG                 108
#define IDD_PRINT_DIALOG                109
#define IDD_REPORT_MANAGER              110
#define IDD_REPORT_BUILDER1             111
#define IDD_REPORT_BUILDER2             112
#define IDD_REPORT_BUILDER3             113
#define IDD_REPORT_BUILDER4             114
#define IDD_REPORT_BUILDER5             115
#define IDD_REPORT_BUILDER6             116
#define IDD_REPORT_BUILDER7             117
#define IDD_REPORT_BUILDER8             118
#define IDD_REPORT_BUILDER9             119
#define IDD_REPORT_BUILDER10            120
#define IDD_REPORT_PREVIEW              130
#define IDD_EXPORT_DATA                 131
#define IDD_VDB_PRINT_REPORT            132
#define IDD_REPORT_CHANGE_COLUMN        133
#define IDD_LIST_CTRL_COLORS            134
#define IDD_REPORT_FORMAT_STYLE         135
#define IDD_TROUBLESHOOT_LOGIN          136
#define IDD_STATUS_WINDOW               137
#define IDD_DATABASE_OPEN               139
#define IDD_DATABASE_NEW                140
#define IDD_DATABASE_DELETE             141
#define IDD_DATABASE_BACKUP             142
#define IDD_DATABASE_RESTORE            143
#define IDD_DATABASE_IMPORT             144
#define IDD_DATABASE_ATTACH             144
#define IDD_DATABASE_EXPORT             145
#define IDB_VDB_DIRECTORY_ICONS         800
#define IDB_VDB_FILE_ICONS              801
#define IDB_VDB_REPORT_FILTER           802
#define IDB_VDB_REPORT_SORT             803
#define IDB_VDB_REPORT_TABLES           804
#define IDB_VDB_DIRECTORY_DISABLED      805
#define IDB_VDB_DIRECTORY_DOWN          806
#define IDB_VDB_DIRECTORY_FOCUS         807
#define IDB_VDB_DIRECTORY_UP            808
#define IDB_VDB_CHECKMARK_BITMAP        809
#define IDB_VDB_SQL_SERVER              810
#define IDB_VDB_CONNECTION_FAILED       813
#define IDB_VDB_ODBC_MANAGER            814
#define IDB_VDB_ACCEPT                  815
#define IDB_VDB_REJECT                  816
#define IDB_VDB_DATABASE                817
#define IDB_VDB_NEW                     818
#define IDB_VDB_NEW_DISABLED            819
#define IDC_VDB_DIRECTORY_TREE          902
#define IDC_VDB_DRIVES                  903
#define IDC_VDB_SELECTED_DIRECTORY      904
#define IDC_VDB_DESCRIPTION             905
#define IDC_VDB_SELECTED_FILE           906
#define IDC_VDB_FILE_TYPES              907
#define IDC_VDB_FILES                   908
#define IDC_VDB_PRINTERS                909
#define IDC_VDB_SETUP                   910
#define IDC_VDB_ALL                     911
#define IDC_VDB_PAGES                   912
#define IDC_VDB_FROM_PAGE               913
#define IDC_VDB_TO_PAGE                 914
#define IDC_VDB_PORTRAIT                915
#define IDC_VDB_LANDSCAPE               916
#define IDC_VDB_LIST_STYLES             917
#define IDC_VDB_FORMAT_STYLE            918
#define IDC_VDB_FONT_FACE               930
#define IDC_VDB_CATEGORY                931
#define IDC_VDB_FONT_SIZE               932
#define IDC_VDB_FONT_COLOR              933
#define IDC_VDB_SAMPLE                  934
#define IDC_VDB_FONT_STYLE              935
#define IDC_VDB_CATEGORY_DESC           936
#define IDC_VDB_FONT_FACE_DESC          937
#define IDC_VDB_FONT_STYLE_DESC         938
#define IDC_VDB_FONT_SIZE_DESC          939
#define IDC_VDB_FONT_COLOR_DESC         940
#define IDC_VDB_LIST_SOURCES            941
#define IDC_VDB_IDENTIFICATION          942
#define IDC_VDB_PASSWORD                943
#define IDC_VDB_DATASOURCE              944
#define IDC_VDB_SQL_SERVER_MANAGER      945
#define IDC_VDB_ODBC_MANAGER            946
#define IDC_VDB_CLOSE                   1018
#define IDC_VDB_DATA_DIRECTORY          1024
#define IDC_VDB_TEXT                    1042
#define IDC_VDB_AUTHORIZATION_ID        1049
#define IDC_VDB_DATASOURCE_NAME         1050
#define IDC_VDB_DATABASE_NAME           1051
#define IDC_VDB_DATA_SIZE               1052
#define IDC_VDB_LOG_SIZE                1053
#define IDC_VDB_AUTHORIZATION_PASSWORD  1054
#define IDC_MESSAGE                     1701
#define IDC_USER_INPUT                  1702
#define IDC_EXTRA                       1703
#define IDC_VDB_EDIT                    1801
#define IDC_VDB_MODIFY                  1802
#define IDC_VDB_AND_OR                  1804
#define IDC_VDB_TABLES                  1805
#define IDC_VDB_OPERATOR                1806
#define IDC_VDB_FOREIGN_LIST            1807
#define IDC_VDB_ASCENDING               1808
#define IDC_VDB_DESCENDING              1809
#define IDC_VDB_LIST_DEFS               1810
#define IDC_VDB_FILENAME                1811
#define IDC_VDB_FILTERS                 1812
#define IDC_VDB_TITLE                   1812
#define IDC_VDB_SORTS                   1813
#define IDC_VDB_EXPORT                  1814
#define IDC_VDB_NEW_DATABASE            1815
#define IDC_VDB_PRINT                   1816
#define IDC_VDB_INCLUDE                 1817
#define IDC_VDB_EXCLUDE                 1818
#define IDC_VDB_DISPLAY_WIDTH           1819
#define IDC_VDB_CHANGE                  1820
#define IDC_VDB_DISPLAY_NAME            1821
#define IDC_VDB_HEADER                  1822
#define IDC_VDB_FOOTER                  1823
#define IDC_VDB_LEFT_MARGIN             1824
#define IDC_VDB_RIGHT_MARGIN            1825
#define IDC_VDB_HEADER_COMMANDS         1826
#define IDC_VDB_FOOTER_COMMANDS         1827
#define IDC_VDB_LEFT_MARGIN_COMMANDS    1828
#define IDC_VDB_RIGHT_MARGIN_COMMANDS   1829
#define IDC_VDB_COLUMNS                 1830
#define IDC_VDB_YES_PLEASE              1831
#define IDC_VDB_NO_THANK_YOU            1832
#define IDC_VDB_REMOVE                  1833
#define IDC_VDB_PREVIEW                 1834
#define IDC_VDB_LIST                    1835
#define IDC_VDB_NEW                     1836
#define IDC_VDB_DUPLICATE               1837
#define IDC_VDB_DELETE                  1838
#define IDC_VDB_DIRECTORY               1839
#define IDC_VDB_EXPORT_DIRECTORY        1840
#define IDC_VDB_EXPORT_FILENAME         1841
#define IDC_VDB_COMPARISON_VALUE        1842
#define IDC_VDB_FORMAT_STRING           1843
#define IDC_VDB_CREATE_DIRECTORY        1844
#define IDC_VDB_NEW_DIRECTORY_NAME      1845
#define IDC_VDB_ACCEPT                  1846
#define IDC_VDB_REJECT                  1847
#define IDC_VDB_HIGHLIGHT               1901
#define IDC_VDB_BACKGROUND              1902
#define IDC_VDB_SAMPLE_LIST             1903
#define IDC_VDB_CHOOSE_RECENT           2001
#define IDC_VDB_CHOOSE_ALTERNATE        2002
#define IDC_VDB_RECENT_BACKUPS          2003
#define IDC_VDB_BACKUP_FILE             2004
#define IDC_VDB_SELECT_BACKUP_FILE      2005
#define IDC_VDB_SELECT_DIRECTORY        2006
#define IDC_VDB_DATA_FILE               2100
#define IDC_VDB_SELECT_DATA_FILE        2101
#define IDC_VDB_LOG_FILE                2102
#define IDC_VDB_SELECT_LOG_FILE         2103
#define IDB_VDB_OK                      4201
#define IDB_VDB_CLOSE                   4202

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         2103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
